#!/bin/bash
# ─────────────────────────────────────────────────────────────
# 05-create-nginx-config.sh
# Generate ${NGINX_CONF_DIR}/*.conf for the nginx CONTAINER:
#   00-http-redirect.conf  — :80 → https
#   <domain>.conf          — :443 SSL (certs/<CERT_NAME>.crt) → aem-dispatcher:80
# Files are mounted into nginx:alpine at /etc/nginx/conf.d (see docker-compose.yml).
# ─────────────────────────────────────────────────────────────

set -e
source "$(dirname "$0")/lib/common.sh"

CONF_D="$NGINX_CONF_DIR"
MARKER="Auto-generated by 05-create-nginx-config.sh"
# Paths as seen INSIDE the nginx container (docker-compose.yml mounts
# ${INSTALL_DIR}/certs → /etc/nginx/certs). Not host paths — do not change.
C_CERT="/etc/nginx/certs/${CERT_NAME}.crt"
C_KEY="/etc/nginx/certs/${CERT_NAME}.key"
# Dispatcher is reached over the compose network (service name + container port)
UPSTREAM="http://aem-dispatcher:80"

step "Generating nginx configuration"

[[ -f "$CERT_FILE" ]] || fail "Certificate not found at $(rel "$CERT_FILE"). Run: make certs"

mkdir -p "$CONF_D"

# Remove previously generated files so removed domains disappear
grep -l "$MARKER" "$CONF_D"/*.conf 2>/dev/null | xargs rm -f 2>/dev/null || true

HTTPS_SUFFIX=""
[[ "$NGINX_HTTPS_PORT" != "443" ]] && HTTPS_SUFFIX=":${NGINX_HTTPS_PORT}"

cat > "$CONF_D/00-http-redirect.conf" <<EOF
# ${MARKER} — do not edit, re-run: make nginx
server {
    listen      80 default_server;
    server_name _;
    return      301 https://\$host${HTTPS_SUFFIX}\$request_uri;
}
EOF
ok "${CYAN}$(rel "$CONF_D")/00-http-redirect.conf${RESET}"

for domain in $CUSTOM_DOMAINS; do
  cat > "$CONF_D/${domain}.conf" <<EOF
# ${MARKER} — do not edit, re-run: make nginx
# https://${domain}${HTTPS_SUFFIX} → dispatcher → AEM Publish
server {
    listen       443 ssl;
    http2        on;
    server_name  ${domain};

    # Container paths — docker-compose.yml mounts the host folder
    #   $(rel "$CERTS_DIR")  →  /etc/nginx/certs
    ssl_certificate      ${C_CERT};       # host: $(rel "$CERT_FILE")
    ssl_certificate_key  ${C_KEY};       # host: $(rel "$KEY_FILE")
    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    client_max_body_size 100m;

    location / {
        # Dispatcher container by name on the Docker network aem-local-net, port 80
        # inside it. Same container you reach from the host at localhost:${DISPATCHER_PORT}
        # (inside this container "localhost" would be nginx itself).
        proxy_pass          ${UPSTREAM};
        proxy_http_version  1.1;
        proxy_set_header    Host               \$host;
        proxy_set_header    X-Real-IP          \$remote_addr;
        proxy_set_header    X-Forwarded-For    \$proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Host   \$host;
        proxy_set_header    X-Forwarded-Proto  https;
        proxy_set_header    X-Forwarded-Port   ${NGINX_HTTPS_PORT};
        proxy_read_timeout  120s;
    }
}
EOF
  ok "${CYAN}$(rel "$CONF_D")/${domain}.conf${RESET}"
done

echo ""
for domain in $CUSTOM_DOMAINS; do
  info "${CYAN}https://${domain}${HTTPS_SUFFIX}${RESET} → aem-dispatcher:80 (host :${DISPATCHER_PORT}) → publish :${AEM_PUBLISH_PORT}"
done
echo ""
