#!/bin/bash
# ─────────────────────────────────────────────────────────────
# scripts/uninstall.sh [-y]
# Revert everything `make` created. Keeps: SDK zip, .env, source files.
#   Docker : aem-nginx, aem-dispatcher, aem-local-net, cache volume, their images
#   Host   : AEM processes, "# stackisle" lines in the hosts file
#   Files  : instances in AUTHOR_DIR/PUBLISH_DIR, unpacked SDK in SDK_DIR,
#            cert, generated nginx conf, dispatcher image ref + log + validator cache,
#            DISPATCHER_SRC_DIR only if still identical to the SDK default
# Not touched: system packages (Java, Docker, mkcert) — see message at end.
# ─────────────────────────────────────────────────────────────

set -e
source "$(dirname "$0")/lib/common.sh"

step "stackisle uninstall"
info "This removes: containers + images, AEM Author/Publish repositories,"
info "unpacked SDK, generated certs/nginx config, and hosts-file entries."
info "Kept: SDK zip, .env, scripts, customised dispatcher config."
echo ""
if [[ "$1" != "-y" ]]; then
  read -rp "  Type 'yes' to continue: " a
  [[ "$a" == "yes" ]] || { echo "  Aborted."; exit 1; }
fi

# ── Services ─────────────────────────────────────────────────
# Graceful AEM shutdown first — never delete repositories under a running JVM
bash scripts/06-start-aem.sh stop \
  || fail "AEM is still shutting down — nothing was removed. Re-run 'make uninstall' once 'bash scripts/06-start-aem.sh status' shows it stopped."

# ── Validator cache (before images go: may hold root-owned files) ──
if [[ -d "$DISPATCHER_CACHE_DIR" ]]; then
  rm -rf "$DISPATCHER_CACHE_DIR" 2>/dev/null || true
  if [[ -d "$DISPATCHER_CACHE_DIR" ]] && docker info &>/dev/null && [[ -f "$DISPATCHER_IMAGE_FILE" ]]; then
    # Files written by the container are owned by root — delete them from inside one
    ( source "$DISPATCHER_IMAGE_FILE"
      docker run --rm --entrypoint /bin/sh -v "$DISPATCHER_CACHE_DIR":/c "$DISPATCHER_IMAGE" \
        -c 'rm -rf /c/* /c/.[!.]* 2>/dev/null; true' ) || true
    rmdir "$DISPATCHER_CACHE_DIR" 2>/dev/null || true
  fi
  [[ -d "$DISPATCHER_CACHE_DIR" ]] \
    && warn "Could not remove $(rel "$DISPATCHER_CACHE_DIR") — run: sudo rm -rf $(rel "$DISPATCHER_CACHE_DIR")" \
    || ok "Removed validator cache $(rel "$DISPATCHER_CACHE_DIR")"
fi

step "Removing containers, network and images"
if docker info &>/dev/null; then
  compose down --rmi all --volumes --remove-orphans 2>/dev/null || true
  docker network rm aem-local-net &>/dev/null || true
  ok "Docker resources removed."
else
  warn "Docker not reachable — skipped container/image removal."
fi

# ── Hosts file ───────────────────────────────────────────────
bash update-etc-hosts.sh remove || warn "Could not edit hosts file — remove '# stackisle' lines manually."

# ── Dispatcher config (only if unmodified) ───────────────────
# Only named, stackisle-created items are deleted — never whole directories —
# so a mistaken path in .env can't wipe unrelated data.
step "Removing generated files"
DSDK="$(dispatcher_sdk_dir)"
if [[ -n "$(ls -A "$DISPATCHER_SRC_DIR" 2>/dev/null)" ]]; then
  if [[ -n "$DSDK" && -d "$DSDK/src" ]] && diff -rq "$DSDK/src" "$DISPATCHER_SRC_DIR" &>/dev/null; then
    find "$DISPATCHER_SRC_DIR" -mindepth 1 -delete
    ok "$(rel "$DISPATCHER_SRC_DIR") was the unmodified SDK default — removed."
  else
    warn "$(rel "$DISPATCHER_SRC_DIR") has your changes (or no SDK to compare) — kept."
  fi
fi

# ── Files ────────────────────────────────────────────────────
for d in "$AUTHOR_DIR" "$PUBLISH_DIR"; do
  rm -rf "$d/crx-quickstart" "$d"/aem-*-p*.jar "$d/aem.pid"
  ok "Removed instance: $(rel "$d")"
done
find "$SDK_DIR" -mindepth 1 -maxdepth 1 -type d \( -name 'aem-sdk-*' -o -name 'dispatcher-sdk-*' \) -exec rm -rf {} + 2>/dev/null || true
rm -f "$CERT_FILE" "$KEY_FILE" "$CERTS_DIR/.${CERT_NAME}.sans"
grep -l "Auto-generated by 05-create-nginx-config.sh" "$NGINX_CONF_DIR"/*.conf 2>/dev/null | xargs rm -f || true
rm -f "$DISPATCHER_IMAGE_FILE" "$DISPATCHER_LOG_DIR/dispatcher.log"
# Remove now-empty directories outside the project (rmdir only removes empty ones)
for d in "$AUTHOR_DIR" "$PUBLISH_DIR" "$SDK_DIR" "$CERTS_DIR" "$NGINX_CONF_DIR" \
         "$(dirname "$NGINX_CONF_DIR")" "$DISPATCHER_LOG_DIR" "$(dirname "$DISPATCHER_IMAGE_FILE")" \
         "$DISPATCHER_DIR" "$INSTALL_DIR"; do
  [[ "$d" == "$ROOT_DIR"/* ]] || rmdir "$d" 2>/dev/null || true
done
ok "Generated files removed."

echo ""
echo -e "  ${GREEN}${BOLD}Uninstall complete.${RESET} Run ${CYAN}make${RESET} to set up again."
echo ""
info "System packages were NOT removed. If you want them gone too:"
case "$OS" in
  linux) info "  sudo apt remove openjdk-${JAVA_REQUIRED}-jdk   ·   sudo gpasswd -d \$USER docker"
         info "  mkcert -uninstall && sudo apt remove mkcert   (or: sudo rm /usr/local/bin/mkcert)" ;;
  mac)   info "  brew uninstall --cask temurin@${JAVA_REQUIRED}   ·   mkcert -uninstall && brew uninstall mkcert" ;;
  windows) info "  choco uninstall temurin${JAVA_REQUIRED} mkcert" ;;
esac
echo ""
