#!/bin/bash
# ─────────────────────────────────────────────────────────────
# scripts/magento/magento.sh <command>
#
# Magento (Open Source / Adobe Commerce) via Composer, served at
# https://${MAGENTO_DOMAIN} through the shared aem-nginx SSL proxy.
#
# TEST STACK — deliberately NOT wired into the Makefile or `make` yet.
# Config: scripts/magento/magento.env (copy from magento.env.example).
# Everything it creates is tagged/separate, so the AEM scripts never touch it:
#   INSTALL_DIR/magento/            code (src/) + admin credentials
#   INSTALL_DIR/certs/magento.crt   own cert (server.crt untouched)
#   NGINX_CONF_DIR/zz-magento-*.conf own server block (own marker)
#   hosts lines tagged "# stackisle-magento"
#   compose project "stackisle-magento" (containers magento-*, volumes stackisle-magento-*)
#
# Commands (run in this order the first time, or `all`):
#   check      prerequisites, keys, AEM network/nginx
#   build      build the PHP-FPM image (extensions + Composer)
#   up         start db, search, cache, php (waits until healthy)
#   create     composer create-project into INSTALL_DIR/magento/src
#   install    bin/magento setup:install + dev settings, start web
#   ssl        cert + aem-nginx server block + hosts entry
#   status     containers, URLs, HTTP check
#   all        check build up create install ssl status
# Day to day:
#   start | stop            start / gracefully stop all Magento containers
#   logs [service]          follow logs (db, search, cache, php, web)
#   shell                   bash in the PHP container as www-data
#   magento <args>          run bin/magento <args>
#   composer <args>         run composer <args> (repo.magento.com keys passed in)
#   uninstall               remove everything this script created (asks)
# ─────────────────────────────────────────────────────────────

set -e
source "$(dirname "$0")/../lib/common.sh"

MDIR="$ROOT_DIR/scripts/magento"
MENV="$MDIR/magento.env"
if [[ -f "$MENV" ]]; then set -a; source "$MENV"; set +a; fi

: "${MAGENTO_DOMAIN:=dev-local-mc.brand.com}"
: "${MAGENTO_EDITION:=community}"
: "${MAGENTO_VERSION:=}"
: "${MAGENTO_ADMIN_USER:=admin}"
: "${MAGENTO_ADMIN_EMAIL:=admin@example.com}"
: "${MAGENTO_ADMIN_FIRSTNAME:=Admin}"
: "${MAGENTO_ADMIN_LASTNAME:=Local}"
: "${MAGENTO_BACKEND_FRONTNAME:=admin}"
: "${MAGENTO_LANGUAGE:=en_US}"
: "${MAGENTO_CURRENCY:=USD}"
: "${MAGENTO_TIMEZONE:=UTC}"
: "${MAGENTO_DISABLE_2FA:=1}"
: "${MAGENTO_MODE:=developer}"
: "${MAGENTO_DB_NAME:=magento}"
: "${MAGENTO_DB_USER:=magento}"
: "${MAGENTO_DB_PASSWORD:=magento}"

# ── Derived paths (all under INSTALL_DIR, like the AEM stack) ──
MAGENTO_DIR="$INSTALL_DIR/magento"
MAGENTO_SRC_DIR="$MAGENTO_DIR/src"
MAGENTO_CRED_FILE="$MAGENTO_DIR/admin-credentials.txt"
MAGENTO_CERT="$CERTS_DIR/magento.crt"
MAGENTO_KEY="$CERTS_DIR/magento.key"
MAGENTO_NGINX_CONF="$NGINX_CONF_DIR/zz-magento-${MAGENTO_DOMAIN}.conf"
MARKER="Auto-generated by scripts/magento/magento.sh"
HOSTS_TAG="# stackisle-magento"
HOSTS_FILE=/etc/hosts; [[ "$OS" == "windows" ]] && HOSTS_FILE=/c/Windows/System32/drivers/etc/hosts

# Exported for docker-compose.yml
HOST_UID="$(id -u)"; HOST_GID="$(id -g)"
export MAGENTO_SRC_DIR HOST_UID HOST_GID

mcompose() { docker compose -f "$MDIR/docker-compose.yml" --project-directory "$MDIR" "$@"; }
# Run as www-data (= your UID) inside the PHP container
mphp()     { mcompose exec -T -u www-data php "$@"; }
magento()  { mphp php bin/magento "$@"; }
composer_auth() {
  printf '{"http-basic":{"repo.magento.com":{"username":"%s","password":"%s"}}}' \
    "$MAGENTO_PUBLIC_KEY" "$MAGENTO_PRIVATE_KEY"
}
installed() { [[ -f "$MAGENTO_SRC_DIR/app/etc/env.php" ]]; }
aem_nginx_running() { docker ps --format '{{.Names}}' 2>/dev/null | grep -qx aem-nginx; }

# ── check ────────────────────────────────────────────────────
cmd_check() {
  step "Magento — checking prerequisites"
  require_docker
  docker compose version &>/dev/null || fail "Docker Compose v2 not found."
  ok "Docker $(docker --version | awk '{print $3}' | tr -d ,), arch $(docker info --format '{{.Architecture}}')"

  [[ -f "$MENV" ]] || fail "$(rel "$MENV") missing. Run: cp $(rel "$MDIR")/magento.env.example $(rel "$MENV")"
  ok "Config $(rel "$MENV")"
  [[ -n "${MAGENTO_PUBLIC_KEY:-}" && -n "${MAGENTO_PRIVATE_KEY:-}" ]] \
    || fail "MAGENTO_PUBLIC_KEY / MAGENTO_PRIVATE_KEY empty in $(rel "$MENV") (repo.magento.com access keys)."
  ok "repo.magento.com keys set (public ${MAGENTO_PUBLIC_KEY:0:6}…)"

  docker network inspect aem-local-net &>/dev/null \
    || fail "Docker network aem-local-net missing — start the AEM stack first: make start-dispatcher start-nginx"
  ok "Network aem-local-net exists"
  if aem_nginx_running; then ok "aem-nginx running (SSL entry point)"
  else warn "aem-nginx not running — 'ssl' will prepare files; they activate on: make start-nginx"; fi

  local e="$MAGENTO_DIR"; while [[ ! -e "$e" ]]; do e="$(dirname "$e")"; done
  [[ -w "$e" ]] || fail "$(rel "$MAGENTO_DIR") not writable."
  ok "Install path $(rel "$MAGENTO_DIR")"

  info "Edition ${CYAN}${MAGENTO_EDITION}${RESET}, version ${CYAN}${MAGENTO_VERSION:-latest}${RESET}, PHP ${CYAN}${MAGENTO_PHP_VERSION:-8.3}${RESET}"
  info "Domain  ${CYAN}https://${MAGENTO_DOMAIN}${RESET}"
  echo ""
}

# ── build ────────────────────────────────────────────────────
cmd_build() {
  step "Magento — building PHP-FPM image (UID ${HOST_UID}, GID ${HOST_GID})"
  require_docker
  mcompose build php
  ok "Image stackisle/magento-php:${MAGENTO_PHP_VERSION:-8.3} built."
}

# ── up ───────────────────────────────────────────────────────
cmd_up() {
  step "Magento — starting db, search, cache, php"
  require_docker
  mkdir -p "$MAGENTO_SRC_DIR"          # created as you, not by Docker as root
  mcompose up -d --wait db search cache php
  ok "Services healthy."
}

# ── create ───────────────────────────────────────────────────
cmd_create() {
  step "Magento — composer create-project"
  if [[ -f "$MAGENTO_SRC_DIR/composer.json" ]]; then
    ok "Code already present in $(rel "$MAGENTO_SRC_DIR") — skipping."
    return
  fi
  [[ -z "$(ls -A "$MAGENTO_SRC_DIR" 2>/dev/null)" ]] \
    || fail "$(rel "$MAGENTO_SRC_DIR") is not empty but has no composer.json — clean it first."
  local pkg="magento/project-${MAGENTO_EDITION}-edition${MAGENTO_VERSION:+=${MAGENTO_VERSION}}"
  info "Package ${CYAN}${pkg}${RESET} → $(rel "$MAGENTO_SRC_DIR")  (several minutes on first run)"
  mcompose exec -T -u www-data -e COMPOSER_AUTH="$(composer_auth)" php \
    composer create-project --repository-url=https://repo.magento.com/ \
      "$pkg" /var/www/html --no-interaction --no-progress
  ok "Magento code downloaded."
}

# ── install ──────────────────────────────────────────────────
cmd_install() {
  step "Magento — setup:install"
  [[ -f "$MAGENTO_SRC_DIR/bin/magento" ]] || fail "No Magento code yet. Run: create"
  if installed; then
    ok "Already installed ($(rel "$MAGENTO_SRC_DIR")/app/etc/env.php exists) — skipping setup:install."
  else
    local pass="${MAGENTO_ADMIN_PASSWORD:-}"
    if [[ -z "$pass" ]]; then
      # Magento needs letters + digits, >= 7 chars
      pass="$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 14)9a"
    fi
    magento setup:install \
      --base-url="https://${MAGENTO_DOMAIN}/" \
      --base-url-secure="https://${MAGENTO_DOMAIN}/" \
      --use-secure=1 --use-secure-admin=1 --use-rewrites=1 \
      --backend-frontname="${MAGENTO_BACKEND_FRONTNAME}" \
      --db-host=magento-db --db-name="${MAGENTO_DB_NAME}" \
      --db-user="${MAGENTO_DB_USER}" --db-password="${MAGENTO_DB_PASSWORD}" \
      --search-engine=opensearch --opensearch-host=magento-search --opensearch-port=9200 \
      --opensearch-index-prefix=magento2 --opensearch-enable-auth=0 \
      --session-save=redis --session-save-redis-host=magento-cache --session-save-redis-db=2 \
      --cache-backend=redis --cache-backend-redis-server=magento-cache --cache-backend-redis-db=0 \
      --page-cache=redis --page-cache-redis-server=magento-cache --page-cache-redis-db=1 \
      --admin-firstname="${MAGENTO_ADMIN_FIRSTNAME}" --admin-lastname="${MAGENTO_ADMIN_LASTNAME}" \
      --admin-email="${MAGENTO_ADMIN_EMAIL}" --admin-user="${MAGENTO_ADMIN_USER}" \
      --admin-password="${pass}" \
      --language="${MAGENTO_LANGUAGE}" --currency="${MAGENTO_CURRENCY}" --timezone="${MAGENTO_TIMEZONE}" \
      --no-interaction

    ( umask 077
      printf 'URL:      https://%s/%s\nUser:     %s\nPassword: %s\n' \
        "$MAGENTO_DOMAIN" "$MAGENTO_BACKEND_FRONTNAME" "$MAGENTO_ADMIN_USER" "$pass" > "$MAGENTO_CRED_FILE" )
    ok "Installed. Admin credentials saved to $(rel "$MAGENTO_CRED_FILE") (mode 600)."
  fi

  info "Deploy mode: ${MAGENTO_MODE}"
  magento deploy:mode:set "$MAGENTO_MODE" --skip-compilation

  if [[ "$MAGENTO_DISABLE_2FA" == "1" ]]; then
    # Only disable modules this version actually has
    local mods
    mods="$(magento module:status 2>/dev/null | grep -oE 'Magento_(AdminAdobeImsTwoFactorAuth|TwoFactorAuth)' | sort -u | tr '\n' ' ')"
    if [[ -n "$mods" ]]; then
      info "Disabling admin 2FA for local use: ${mods}"
      # shellcheck disable=SC2086
      magento module:disable $mods --clear-static-content
    fi
  fi
  magento cache:flush >/dev/null
  ok "Magento configured."

  mcompose up -d web
  ok "Web container magento-web started (reachable by aem-nginx as http://magento-web:80)."
  echo ""
}

# ── ssl ──────────────────────────────────────────────────────
make_cert() {
  if [[ -f "$MAGENTO_CERT" && -f "$MAGENTO_KEY" && "${FORCE:-0}" != "1" ]] \
     && openssl x509 -in "$MAGENTO_CERT" -noout -text 2>/dev/null | grep -q "DNS:${MAGENTO_DOMAIN}"; then
    ok "Cert $(rel "$MAGENTO_CERT") already covers ${MAGENTO_DOMAIN}."
    return
  fi
  mkdir -p "$CERTS_DIR"
  if command -v mkcert &>/dev/null; then
    mkcert -cert-file "$MAGENTO_CERT" -key-file "$MAGENTO_KEY" "$MAGENTO_DOMAIN" >/dev/null 2>&1
    ok "mkcert certificate $(rel "$MAGENTO_CERT") (trusted by local CA)."
  else
    openssl req -x509 -nodes -newkey rsa:2048 -sha256 -days 825 \
      -keyout "$MAGENTO_KEY" -out "$MAGENTO_CERT" -subj "/CN=${MAGENTO_DOMAIN}" \
      -addext "subjectAltName=DNS:${MAGENTO_DOMAIN}" \
      -addext "extendedKeyUsage=serverAuth" 2>/dev/null
    warn "Self-signed cert $(rel "$MAGENTO_CERT") (browser warning — install mkcert and re-run with FORCE=1)."
  fi
  chmod 644 "$MAGENTO_CERT"; chmod 600 "$MAGENTO_KEY"
}

write_nginx_conf() {
  mkdir -p "$NGINX_CONF_DIR"
  cat > "$MAGENTO_NGINX_CONF" <<EOF
# ${MARKER} — do not edit, re-run: bash scripts/magento/magento.sh ssl
# https://${MAGENTO_DOMAIN} → magento-web:80 (Magento test stack)
server {
    listen       443 ssl;
    http2        on;
    server_name  ${MAGENTO_DOMAIN};

    # Container paths — host: $(rel "$MAGENTO_CERT") / $(rel "$MAGENTO_KEY")
    ssl_certificate      /etc/nginx/certs/magento.crt;
    ssl_certificate_key  /etc/nginx/certs/magento.key;
    ssl_protocols        TLSv1.2 TLSv1.3;

    client_max_body_size 64m;

    # Resolve magento-web at request time via Docker's DNS, so aem-nginx still
    # starts and serves the AEM sites when the Magento stack is stopped.
    resolver 127.0.0.11 valid=10s ipv6=off;
    set \$magento_upstream http://magento-web:80;

    location / {
        proxy_pass          \$magento_upstream;
        proxy_http_version  1.1;
        proxy_set_header    Host               \$host;
        proxy_set_header    X-Real-IP          \$remote_addr;
        proxy_set_header    X-Forwarded-For    \$proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Host   \$host;
        proxy_set_header    X-Forwarded-Proto  https;   # Magento's default SSL offloader header
        proxy_set_header    X-Forwarded-Port   443;
        proxy_read_timeout  300s;
        # Magento sends large headers (cookies, cache tags)
        proxy_buffer_size        128k;
        proxy_buffers            4 256k;
        proxy_busy_buffers_size  256k;
    }
}
EOF
  ok "nginx server block $(rel "$MAGENTO_NGINX_CONF")"
}

reload_aem_nginx() {
  aem_nginx_running || { warn "aem-nginx not running — config activates on: make start-nginx"; return; }
  if docker exec aem-nginx nginx -t >/dev/null 2>&1; then
    docker exec aem-nginx nginx -s reload >/dev/null
    ok "aem-nginx config test passed and reloaded."
  else
    docker exec aem-nginx nginx -t || true
    rm -f "$MAGENTO_NGINX_CONF"
    fail "aem-nginx rejected the Magento config — removed it again, AEM sites unaffected."
  fi
}

hosts_has() {
  grep -qE "^[[:space:]]*127\.0\.0\.1([[:space:]]+[^[:space:]#]+)*[[:space:]]+${1//./\\.}([[:space:]]|#|$)" "$HOSTS_FILE"
}

cmd_ssl() {
  step "Magento — SSL domain https://${MAGENTO_DOMAIN}"
  make_cert
  write_nginx_conf
  reload_aem_nginx
  if hosts_has "$MAGENTO_DOMAIN"; then
    ok "${MAGENTO_DOMAIN} already in ${HOSTS_FILE}"
  else
    printf '127.0.0.1\t%s\t%s\n' "$MAGENTO_DOMAIN" "$HOSTS_TAG" | as_root tee -a "$HOSTS_FILE" >/dev/null
    ok "Added 127.0.0.1 ${MAGENTO_DOMAIN} to ${HOSTS_FILE} (tag '${HOSTS_TAG}')"
  fi
  echo ""
}

# ── status ───────────────────────────────────────────────────
cmd_status() {
  step "Magento — status"
  mcompose ps
  echo ""
  local code
  code="$(http_code --resolve "${MAGENTO_DOMAIN}:443:127.0.0.1" "https://${MAGENTO_DOMAIN}/")"
  [[ "$code" =~ ^[23] ]] && ok "https://${MAGENTO_DOMAIN}/ → HTTP ${code}" \
                         || warn "https://${MAGENTO_DOMAIN}/ → HTTP ${code}"
  info "Storefront ${CYAN}https://${MAGENTO_DOMAIN}/${RESET}"
  info "Admin      ${CYAN}https://${MAGENTO_DOMAIN}/${MAGENTO_BACKEND_FRONTNAME}${RESET}  (credentials: $(rel "$MAGENTO_CRED_FILE"))"
  echo ""
}

# ── start / stop / logs / shell / passthrough ───────────────
cmd_start() {
  step "Magento — starting"
  mkdir -p "$MAGENTO_SRC_DIR"
  if installed; then mcompose up -d --wait; else mcompose up -d --wait db search cache php; fi
  ok "Started."
}
cmd_stop() {
  step "Magento — stopping gracefully"
  # SIGTERM, then each service's stop_grace_period (db/search: 2m) — no instant kill
  mcompose stop
  ok "Stopped. Data kept in volumes stackisle-magento-db / -search."
}

# ── uninstall ────────────────────────────────────────────────
cmd_uninstall() {
  step "Magento — uninstall"
  info "Removes: magento-* containers, stackisle-magento-* volumes (database, search index,"
  info "composer cache), the PHP image, the nginx server block, the cert and the hosts entry."
  read -rp "  Type 'yes' to continue: " a; [[ "$a" == "yes" ]] || { echo "  Aborted."; exit 1; }

  if docker info &>/dev/null; then
    mcompose stop 2>/dev/null || true            # graceful first
    mcompose down --volumes --remove-orphans 2>/dev/null || true
    docker rmi "stackisle/magento-php:${MAGENTO_PHP_VERSION:-8.3}" &>/dev/null || true
    ok "Containers, volumes, network and PHP image removed."
    info "Pulled images kept (shared/reusable): ${MAGENTO_DB_IMAGE:-mariadb:11.4}, ${MAGENTO_OPENSEARCH_IMAGE:-opensearchproject/opensearch:2.19.1}, ${MAGENTO_REDIS_IMAGE:-redis:7.2-alpine}"
  fi

  if grep -q "$MARKER" "$MAGENTO_NGINX_CONF" 2>/dev/null; then
    rm -f "$MAGENTO_NGINX_CONF"
    aem_nginx_running && docker exec aem-nginx nginx -s reload >/dev/null 2>&1 || true
    ok "nginx server block removed."
  fi
  rm -f "$MAGENTO_CERT" "$MAGENTO_KEY"
  ok "Cert removed."

  if grep -q "${HOSTS_TAG}\$" "$HOSTS_FILE" 2>/dev/null; then
    local tmp; tmp="$(mktemp)"
    grep -v "${HOSTS_TAG}\$" "$HOSTS_FILE" > "$tmp" || true
    [[ -s "$tmp" ]] || { rm -f "$tmp"; fail "Refusing to write an empty ${HOSTS_FILE}."; }
    as_root cp "$HOSTS_FILE" "${HOSTS_FILE}.stackisle-magento.bak"
    as_root cp "$tmp" "$HOSTS_FILE"; rm -f "$tmp"
    ok "Hosts entry removed (backup ${HOSTS_FILE}.stackisle-magento.bak)."
  fi

  if [[ -d "$MAGENTO_SRC_DIR" ]]; then
    read -rp "  Also delete the Magento code in $(rel "$MAGENTO_SRC_DIR")? (yes/no): " a
    if [[ "$a" == "yes" ]]; then
      rm -rf "$MAGENTO_SRC_DIR" "$MAGENTO_CRED_FILE"
      rmdir "$MAGENTO_DIR" 2>/dev/null || true
      ok "Code removed."
    else
      info "Code kept."
    fi
  fi
  echo ""
}

# ── dispatch ─────────────────────────────────────────────────
cmd="${1:-help}"; shift || true
case "$cmd" in
  check)     cmd_check ;;
  build)     cmd_build ;;
  up)        cmd_up ;;
  create)    cmd_create ;;
  install)   cmd_install ;;
  ssl)       cmd_ssl ;;
  status)    cmd_status ;;
  all)       cmd_check; cmd_build; cmd_up; cmd_create; cmd_install; cmd_ssl; cmd_status ;;
  start)     cmd_start ;;
  stop)      cmd_stop ;;
  logs)      mcompose logs -f --tail=200 "$@" ;;
  shell)     mcompose exec -u www-data php bash ;;
  magento)   mcompose exec -u www-data php php bin/magento "$@" ;;
  composer)  mcompose exec -u www-data -e COMPOSER_AUTH="$(composer_auth)" php composer "$@" ;;
  uninstall) cmd_uninstall ;;
  *) sed -n '3,33p' "$0" | sed 's/^# \{0,1\}//' ;;
esac
